---
title: "Economic Shocks and Civil War"
author: "Erin Cavanagh"
description: "Observing the possible relationship between economic shocks to a state' oil market and the liklihood of civil war"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

Research Question: Are countries that suffer from economic shocks more at risk for civil war outbreaks?

Hypothesis: The grievance of Economic shocks to sovereign states leads to the increased likelihood of a civil war conflict. 

Theory: Civil Wars are often the result of collective grievances that motivate a group to rebel. In the wake of economic shocks, people suffer from financial constraints and the continuation of labor under these circumstances appears less attractive. If a change in production lowers wages in an area, the opportunity cost of joining rebel groups is lowered (so long as the individual believes that there will be a gain in doing so). Furthermore, an increase in prices– specifically those of the oil market– can lead to rapacity and violence. Thus, states that depend on the exportation of oil for a portion of their GDP will be more sensitive to the effects of economic shocks on internal conflicts. While there are confounding variables (mountainous terrain, varying state capacities, etc.) I expect to see a relationship between economic shocks and the outbreak of civil war. 

Explanatory Variable: I plan on using the variables that represent the countries oil exportation and GDP as the variables to be manipulated. I will use data from multiple nations and compare the likelihood of civil war as the production and exportation of oil changes. 

Outcome Variable: the outcome variable is the presence of civil conflicts within a nation. The data set includes variables that show the year a civil war started in the country, as well as variables that tell if there is a civil war in the current year or the previous year. 

Observed Patterns: I am looking to see a relationship between a change in the oil exportation (or percentage of the GDP that comes from oil production) and the onset of civil war. In a regression model, I expect that a major shift would result in a civil conflict beginning soon after (models show that civil wars would be the result of both increases and decreases to the price of oil due to opportunity costs and rapacity. I would need to do further research to decide which model I will be using to assess the data.)


To investigate this relationship, I will begin by researching the following databases:

1.  https://www.dropbox.com/s/gde30hr9yokqku5/civilwar.csv?dl=0 

 
```{r}
library(readr)
library(tidyverse)

civilwar <- read_csv("civilwar.csv")
civilwar
cor(civilwar$lngdp_, civilwar$warsa, use = "pairwise")

oil_war_plot <- civilwar|>
  group_by(nafrme)|>
  ggplot(aes(x= lngdp_, y= warsa))+
  geom_smooth(method ="loess", se = TRUE, size= 1.1)+
  labs(title = "Log of GDP per capita and Civil War in the Middle East", x= "Log per capita Income", y ="Onset of Civil War (in 5 year period)")

oil_war_plot
  

```





